# Generated by Django 5.1.3 on 2025-02-05 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posperformance',
            name='posdowntime',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='posperformance',
            name='posuptime',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
