# Generated by Django 5.1.3 on 2025-02-05 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_posperformance_posdowntime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plu2checklist',
            name='customercount',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='plu2checklist',
            name='zread',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='plu2checklist',
            name='comparisonCheck',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
