# Generated by Django 5.1.3 on 2025-02-06 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_saleposting_cashiershortexcess_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleposting',
            name='exception',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
