# Generated by Django 5.1.3 on 2025-02-06 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_saleposting_exception'),
    ]

    operations = [
        migrations.AddField(
            model_name='idtregister',
            name='assistedby',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
