# Generated by Django 5.1.3 on 2025-02-11 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_idtregister_assistedby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backupdetail',
            name='dateCopied',
        ),
        migrations.RemoveField(
            model_name='backupdetail',
            name='fileName',
        ),
        migrations.RemoveField(
            model_name='backupdetail',
            name='size',
        ),
    ]
