# Generated by Django 5.1.3 on 2025-02-11 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_backupdetail_datecopied_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aduserstatus',
            name='filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
