# Generated by Django 5.1.3 on 2025-02-18 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_aduserstatus_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='plu2checklist',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plu2checklist',
            name='verifiedby',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
