# Generated by Django 5.1.3 on 2025-02-18 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_plu2checklist_verified_plu2checklist_verifiedby'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='assitincharge',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='assitinchargeID',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='itincharge',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='itinchargeID',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
