# Generated by Django 5.1.3 on 2025-02-18 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_store_assitincharge_store_assitinchargeid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='assitinchargeID',
            new_name='itmanager',
        ),
        migrations.RemoveField(
            model_name='store',
            name='itinchargeID',
        ),
    ]
