# Generated by Django 5.1.3 on 2025-02-18 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_assitinchargeid_store_itmanager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='acronicsbackup',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='acronicsbackup',
            name='verifiedby',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aduserstatus',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aduserstatus',
            name='verifiedby',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='idtregister',
            name='verifiedby',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='indstorebackup',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='indstorebackup',
            name='verifiedby',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pdtstatus',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pdtstatus',
            name='verifiedby',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='posdbbackup',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='posdbbackup',
            name='verifiedby',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='posperformance',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='posperformance',
            name='verifiedby',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='posstatus',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='posstatus',
            name='verifiedby',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='saleposting',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='saleposting',
            name='verifiedby',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='salestatus',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salestatus',
            name='verifiedby',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='scalestatus',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scalestatus',
            name='verifiedby',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='serverstatus',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='serverstatus',
            name='verifiedby',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='serverstorage',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='serverstorage',
            name='verifiedby',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='upsstatus',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='upsstatus',
            name='verifiedby',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='zvchrstatus',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='zvchrstatus',
            name='verifiedby',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
