# Generated by Django 5.1.3 on 2025-02-18 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_acronicsbackup_verified_acronicsbackup_verifiedby_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='admin_manager',
            field=models.CharField(blank=True, default='Sreejith CS', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='cio',
            field=models.CharField(blank=True, default='Anil Menon', max_length=255, null=True),
        ),
    ]
