# Generated by Django 5.1.3 on 2025-02-22 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_store_admin_manager_store_cio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storecode', models.CharField(max_length=100)),
                ('employeeid', models.CharField(max_length=255)),
                ('designation', models.CharField(blank=True, max_length=255, null=True)),
                ('submitted_time', models.DateTimeField()),
                ('cio', models.CharField(blank=True, default='Anil Menon', max_length=255, null=True)),
                ('admin_manager', models.CharField(blank=True, default='Sreejith CS', max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='backupdetail',
            name='failed_dates',
            field=models.JSONField(default=list),
        ),
    ]
