# Generated by Django 5.1.3 on 2025-02-22 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_profile_backupdetail_failed_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='storeunder',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
