# Generated by Django 5.1.3 on 2025-02-28 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_profile_storeunder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posdbbackup',
            name='size',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
