# Generated by Django 5.1.3 on 2025-03-21 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_posdbbackup_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupDetailVerified',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.CharField(blank=True, max_length=10, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='backups/')),
                ('reviewMonth1', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='backupdetail',
            name='reviewMonth',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
