# Generated by Django 5.2 on 2025-05-03 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_backupdetailverified_backupdetail_reviewmonth'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupdetail',
            name='year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='backupdetailverified',
            name='year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
