# Generated by Django 5.2 on 2025-05-28 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_backupdetail_year_backupdetailverified_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupdetail',
            name='success_dates',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
