# Generated by Django 5.2 on 2025-09-03 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_backupdetail_success_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plu2checklist',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='plu2checklist',
            name='store',
            field=models.CharField(db_index=True, max_length=10),
        ),
    ]
