# Generated by Django 5.2 on 2025-09-03 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_plu2checklist_date_alter_plu2checklist_store'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='plu2checklist',
            index=models.Index(fields=['store', 'date'], name='api_plu2che_store_5e7767_idx'),
        ),
    ]
