# Generated by Django 5.2 on 2025-09-03 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_plu2checklist_api_plu2che_store_5e7767_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acronicsbackup',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='acronicsbackup',
            name='store',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='view_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='aduserstatus',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='aduserstatus',
            name='store',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='backupdetail',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='backupdetail',
            name='site',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='backupdetailverified',
            name='store',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='expenseclaim',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='idtregister',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='idtregister',
            name='store',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='indstorebackup',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='indstorebackup',
            name='store',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='invoicestatus',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='pdtstatus',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='pdtstatus',
            name='store',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='posdbbackup',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='posdbbackup',
            name='store',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='pospdtscale',
            name='store',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='posperformance',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='posperformance',
            name='store',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='posstatus',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='posstatus',
            name='store',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='storecode',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='saleposting',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='saleposting',
            name='store',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='salestatus',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='salestatus',
            name='store',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='scalestatus',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='scalestatus',
            name='store',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='server',
            name='store',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='serverstatus',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='serverstatus',
            name='store',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='serverstorage',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='serverstorage',
            name='store',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='store',
            name='storecode',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='ups',
            name='store',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='upsstatus',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='upsstatus',
            name='store',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='zvchrstatus',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='zvchrstatus',
            name='store',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='acronicsbackup',
            index=models.Index(fields=['store', 'date'], name='api_acronic_store_fbf15f_idx'),
        ),
        migrations.AddIndex(
            model_name='aduserstatus',
            index=models.Index(fields=['store', 'date'], name='api_adusers_store_229f57_idx'),
        ),
        migrations.AddIndex(
            model_name='backupdetail',
            index=models.Index(fields=['site', 'date'], name='api_backupd_site_114c36_idx'),
        ),
        migrations.AddIndex(
            model_name='idtregister',
            index=models.Index(fields=['store', 'date'], name='api_idtregi_store_96c901_idx'),
        ),
        migrations.AddIndex(
            model_name='indstorebackup',
            index=models.Index(fields=['store', 'date'], name='api_indstor_store_743621_idx'),
        ),
        migrations.AddIndex(
            model_name='pdtstatus',
            index=models.Index(fields=['store', 'date'], name='api_pdtstat_store_3b1f2c_idx'),
        ),
        migrations.AddIndex(
            model_name='posdbbackup',
            index=models.Index(fields=['store', 'date'], name='api_posdbba_store_bcaa15_idx'),
        ),
        migrations.AddIndex(
            model_name='posperformance',
            index=models.Index(fields=['store', 'date'], name='api_posperf_store_ffd1f9_idx'),
        ),
        migrations.AddIndex(
            model_name='posstatus',
            index=models.Index(fields=['store', 'date'], name='api_posstat_store_cc668d_idx'),
        ),
        migrations.AddIndex(
            model_name='saleposting',
            index=models.Index(fields=['store', 'date'], name='api_salepos_store_825573_idx'),
        ),
        migrations.AddIndex(
            model_name='salestatus',
            index=models.Index(fields=['store', 'date'], name='api_salesta_store_6b3ac4_idx'),
        ),
        migrations.AddIndex(
            model_name='scalestatus',
            index=models.Index(fields=['store', 'date'], name='api_scalest_store_3fbd53_idx'),
        ),
        migrations.AddIndex(
            model_name='serverstatus',
            index=models.Index(fields=['store', 'date'], name='api_servers_store_257c6e_idx'),
        ),
        migrations.AddIndex(
            model_name='serverstorage',
            index=models.Index(fields=['store', 'date'], name='api_servers_store_c843b4_idx'),
        ),
        migrations.AddIndex(
            model_name='upsstatus',
            index=models.Index(fields=['store', 'date'], name='api_upsstat_store_b62b08_idx'),
        ),
        migrations.AddIndex(
            model_name='zvchrstatus',
            index=models.Index(fields=['store', 'date'], name='api_zvchrst_store_5acf82_idx'),
        ),
    ]
