# Generated by Django 5.2 on 2025-09-10 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_acronicsbackup_date_alter_acronicsbackup_store_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pospdtscale',
            name='type',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='pospdtscale',
            index=models.Index(fields=['store', 'type'], name='api_pospdts_store_549c38_idx'),
        ),
    ]
