# Generated by Django 5.2 on 2025-09-10 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_pospdtscale_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='actionlog',
            index=models.Index(fields=['view_name', 'timestamp'], name='api_actionl_view_na_57756a_idx'),
        ),
    ]
